spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social-api?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456aA@
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  #Liquibase properties
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  #Redis properties
  redis:
    host: localhost
    port: 6379
#JWT properties
social:
  jwt:
    header:
      value: Authorization
      prefix: Bearer
    secret: kyrios
    expiration: 3600000