#Database properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social-api?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456aA@
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    banner-mode: console
  #Liquibase properties
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  #Redis properties
  redis:
    database: 0
    host: localhost
    port: 6379
    connect-timeout: 30
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#JWT properties
social:
  jwt:
    header:
      value: Authorization
      prefix: Bearer
    secret: kyrios
    expiration: 18000000
#Logging properties
logging:
  level:
    ROOT: INFO
    com.social.socialserviceapp: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#Token properties
token:
  password:
    reset:
      duration: 3600000
